version: 2.1
orbs:
  utils: arrai/utils@1.8.0
  flake8: arrai/flake8@11.0.1
executors:
  python36:
    environment:
      LANG: C.UTF-8
      COVERAGE_PROCESS_START: .coveragerc
    docker:
     - image: cimg/python:3.6
  python37:
    environment:
      LANG: C.UTF-8
      COVERAGE_PROCESS_START: .coveragerc
    docker:
     - image: cimg/python:3.7
  python38:
    environment:
      LANG: C.UTF-8
      COVERAGE_PROCESS_START: .coveragerc
    docker:
     - image: cimg/python:3.8
  python39:
    environment:
      LANG: C.UTF-8
      COVERAGE_PROCESS_START: .coveragerc
    docker:
     - image: cimg/python:3.9
jobs:
  pythontests:
    parameters:
      executor:
        description: "Execution environment for the test job."
        type: executor
        default: python36
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run:
          description: "Install additional packages."
          command: |
            sudo apt-get update
            sudo apt-get install rsync
      - utils/add_ssh_config:
          host: "docs"
          hostname: ${DOCS_HOST}
          port: ${DOCS_PORT}
          user: ${DOCS_USER}
      - utils/make_status_shield:
          status: running
          color: lightblue
      - run:
          description: "Set up environment."
          command: |
            pip install -r requirements.txt -r test_requirements.txt | cat; test ${PIPESTATUS[0]} -eq 0
            echo "import coverage; coverage.process_startup()" > `python -c "import sys; print([x for x in sys.path if x.find('site-packages') != -1][0] + '/coverage-all-the-things.pth')"`
      - run:
          description: "Run tests."
          command: |
            coverage run -p -m unittest
      - run:
          description: "Combine coverage."
          when: always
          command: |
            coverage combine -a
            coverage html
            coverage report | grep -oP '^TOTAL.*\d' | awk '{print $NF}' >> /tmp/.coveragep
      - utils/rsync_folder:
          when: always
          folder: ./htmlcov/
          remote_folder: ${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}
          host: docs
      - utils/make_coverage_shield:
          when: always
          link: "https://${DOCS_HOST}/shy-sentry/artifacts/${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}/"
      - utils/rsync_file:
          when: always
          file: /tmp/coverage.svg
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.coverage.svg
          host: docs
      - run:
          when: always
          command: pip freeze > ~/pip.freeze
      - utils/rsync_file:
          when: always
          file: ~/pip.freeze
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.freeze
          host: docs
      - utils/make_status_shield:
          when: on_success
          status: passed
          color: brightgreen
      - utils/make_status_shield:
          when: on_fail
          status: failed
          color: red
      - utils/rsync_file:
          when: always
          file: ~/status.svg
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
          host: docs
workflows:
  test:
    jobs:
      - pythontests:
          name: python36
          context: arrai-global
          executor: python36
      - pythontests:
          name: python37
          context: arrai-global
          executor: python37
      - pythontests:
          name: python38
          context: arrai-global
          executor: python38
      - pythontests:
          name: python39
          context: arrai-global
          executor: python39
      - flake8/flake8:
          name: flake8
          context: arrai-global
          wd: ~/project
          flake8_cmd: pflake8
          executor: flake8/python38
